### PR TITLE
Release v8.2.1

### PR DESCRIPTION
**Pull request by aaronpowell**
Moved all the unshipped APIs to shipped to release

### CODE REVIEW

**Review by Alirexaa — APPROVED** [review]
LGTM.
Did you use https://github.com/CommunityToolkit/Aspire/blob/main/eng%2Fapicompat%2Fmark-shipped.cmd for this?

**Comment by aaronpowell** [comment]
No, I had Copilot generate me a bash script as I am on Linux not Windows so don't have cmd or PowerShell.

I should put a bash script in there rather than generating one 🤣

**Comment by Alirexaa** [comment]
@aaronpowell, We should keep `release/*` branches in case patch updates.

**Comment by aaronpowell** [comment]
> @aaronpowell, We should keep `release/*` branches in case patch updates.

We've got the tag on the SHA that was used to trigger the build that generated the NuGet packages, we can always branch off there.

**Pull request merged**
