### PR TITLE
Silent vulnerable package warning

### PR DESCRIPTION
**Pull request by Alirexaa**
**Closes #<ISSUE_NUMBER>**

## PR Checklist

- [ ] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [ ] Based off latest main branch of toolkit
- [ ] PR doesn't include merge commits (always rebase on top of our main, if needed)
- [ ] New integration
  - [ ] Docs are written
  - [ ] Added description of major feature to project description for NuGet package (4000 total character limit, so don't push entire description over that)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Every new API (including internal ones) has full XML docs
- [ ] Code follows all style conventions

### CODE REVIEW

**Comment by Alirexaa** [comment]
@aaronpowell,

following error case build fail:
```
/home/runner/.nuget/packages/msbuild.sdk.sqlproj/2.9.1/Sdk/Sdk.targets(100,5): error : The current SDK bundles target framework '9.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0, or file an issue at https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/ to add support. If you have preview SDKs installed, you may have to use a global.json file: https://docs.microsoft.com/dotnet/core/tools/global-json [/home/runner/work/Aspire/Aspire/examples/sql-database-projects/SdkProject/SdkProject.csproj]
```
Any idea?

**Comment by aaronpowell** [comment]
@ErikEJ @jmezach do we need to upgrade SQL SDK?

**Comment by aaronpowell** [comment]
Looks like we need to upgrade to the 3.0 release of the SQL SDK. This is because we build with .NET 9 on the runners and now it's not preview it is the primary .NET SDK that is used, but the 2.9.1 SQL SDK doesn't support .NET 9 and thus errors.

I've done that upgrade as looking at the issues it seems that 3.0 has just been waiting for the .NET 9 GA to drop the `-beta.2` tag.

**Review by aaronpowell — APPROVED** [review]

**Comment by ErikEJ** [comment]
@aaronpowell yes, we will release 3.0.0 very soon

**Comment by aaronpowell** [comment]
Once it's done and the package is published can you update the project file to drop `-beta.2` please?

I didn't dig into it completely but I'm assuming it's just a "quirk" of how the SDK Project types are handled with respect to .NET versions.

Also, I noticed that the 3.0.0 package is only .NET 9, would it not make more sense to use multiple TFM's?

**Comment by ErikEJ** [comment]
@aaronpowell It is a bit more complex, we have a command line tool that targets multiple .NET versions, called by the Build SDK . Where do you see NET 9.0 only?

**Comment by aaronpowell** [comment]
ah wait, my bad, I thought the nupkg was only .NET 9 but no, I must've been thinking of something else (I've been inside soooooo many nupkgs today 🤣)

**Comment by ErikEJ** [comment]
@aaronpowell PR created: https://github.com/CommunityToolkit/Aspire/pull/232

**Pull request merged**
