### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ErikEJ**
Fix copy paste

### CODE REVIEW

**Review by Alirexaa — APPROVED** [review]

**Comment by Alirexaa** [comment]
@aaronpowell, CodeQL blocks merging PR like this.

**Comment by aaronpowell** [comment]
Yeah I can't figure out how to force a CodeQL run - but for things like this you can override

**Comment by Alirexaa** [comment]
> Yeah I can't figure out how to force a CodeQL run - but for things like this you can override

I can not merge PRs before all checks are passed.

**Comment by aaronpowell** [comment]
oh, I should check your permissions

**Pull request merged**
