### PR TITLE
#254 small fixes for compilation warnings

### LINKED ISSUE #254: [Bug] Compilation errors/warnings
I get different warnings/errors in Rider:
- ConformanceTest.cs line 66: param key is missing in XML documentation
- MeilisearchPublicApiTests line 80: nullable warning
- RustAppPublicApiTests line 26: nullable warning
- RustAppPublicApiTests line 39: nullable warning
- UvicornAppHostingExtension line 18: param name is args, not scriptArgs (XML documentation)

Should we also document that the build of the Java hosting depends on JDK17 and maven?

### PR DESCRIPTION
**Pull request by anoordover**
**Closes #254 **

## PR Checklist

- [X] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [X] Based off latest main branch of toolkit
- [X] PR doesn't include merge commits (always rebase on top of our main, if needed)
- [X] Contains **NO** breaking changes
- [X] Code follows all style conventions

## Other information

Fixes a few minor warnings during compilation.

### CODE REVIEW

**Comment by aaronpowell** [comment]
I noticed a few XML doc comment issues fixes in this PR, and looking into it, it seems that there's a problem which is causing the doc comment errors to not fail the build (which it should), so I've reported #258.

Regarding the .NET issues, I don't see them as compilation warnings, can you show the build output that reports them as warnings? I'm dev'ing across VS and VS Code and don't see it on either, so I'm wondering what Rider is doing differently.

**Comment by anoordover** [comment]
image

**Comment by anoordover** [comment]
I added two screenshots. I think these are warnings in Rider. I can add screenshots of the other warnings as well. Let me know if you want me to do that.

**Review by aaronpowell — APPROVED** [review]

**Comment by anoordover** [comment]
Thanks for the merge!

**Pull request merged**
