### PR TITLE
Adding `ResourceName` attribute to our extension methods

### LINKED ISSUE #89: Add `ResourceNameAttribute` to the resource name arguments on integrations
This is a new attribute in Aspire 9 and while it doesn't appear to be used _yet_, it's setting the ground work for analyzers in the future.

### PR DESCRIPTION
**Pull request by aaronpowell**
Does require a bit of hackery in the tests to tell the analyser to be quiet but that's ok.

Fixes #89

### CODE REVIEW

**Comment by Alirexaa** [comment]
> Does require a bit of hackery in the tests to tell the analyser to be quiet but that's ok.

We could use `NoWarn` in tests.
```xml
<PropertyGroup>
  <NoWarn>ASPIRE006</NoWarn>
</PropertyGroup>
```

**Review by Alirexaa — APPROVED** [review]
I like to see `Resource` classes annotated by this attribute but it seems the analyser doesn't work with classes.
``` csharp
public class JavaAppContainerResource([ResourceName] string name, string? entrypoint = null)
    : ContainerResource(name, entrypoint), IResourceWithServiceDiscovery
{
    internal const string HttpEndpointName = "http";
}
```
but this LGTM

**Comment by aaronpowell** [comment]
> > Does require a bit of hackery in the tests to tell the analyser to be quiet but that's ok.
> 
> We could use `NoWarn` in tests.
> 
> ```
> <PropertyGroup>
>   <NoWarn>ASPIRE006</NoWarn>
> </PropertyGroup>
> ```

That was a thought I had but I think it's best that we avoid having too much `NoWarn` in place because that is a good way to hide away stuff that we _probably_ should know about. Same reason why I did inline disabling of CTASPIRE001 in the tests rather than `NoWarn` on it.

**Comment by aaronpowell** [comment]
> I like to see `Resource` classes annotated by this attribute but it seems the analyser doesn't work with classes.
> 
> ```cs
> public class JavaAppContainerResource([ResourceName] string name, string? entrypoint = null)
>     : ContainerResource(name, entrypoint), IResourceWithServiceDiscovery
> {
>     internal const string HttpEndpointName = "http";
> }
> ```
> 
> but this LGTM

Currently, the Aspire core hosting integrations don't do this, see https://github.com/dotnet/aspire/blob/269864e6fac3fd843072e676b2e87131899710be/src/Aspire.Hosting.PostgreSQL/PostgresServerResource.cs#L23 as an example

So I think it's best that we don't add it so we're consistent with how the core integrations are written.

**Pull request merged**
