### PR TITLE
Fix Ollama GPU support

### LINKED ISSUE #306: Ollama .WithGPUSupport() not working
### Describe the bug

When using the `.WithGPUSupport()` extension on the `IResourceBuilder<OllamaResource>`, the container does not start and logs the error:
```
2024-12-02T23:21:48 Error: unknown flag: --gpus
```

### Regression

_No response_

### Steps to reproduce

```text
1. Create a new empty aspire project.
2. In `Program.cs` in the `AppHost` project add the following:

var builder = DistributedApplication.CreateBuilder(args);

builder
    .AddOllama("ollama")
    .WithGPUSupport();

builder.Build().Run();

3. Observe that the resource does not start
4. Observe the logged error
```

### Expected behavior

The Ollama contain should start and should have the relevant container arguments applied.

### Screenshots

Image

Image

### IDE and version

VS 2022 Preview

### IDE version

_No response_

### Nuget packages

```text
CommunityToolkit.Aspire.Hosting.Ollama (9.0.1-beta.92)
```

### Additional context

_No response_

### Help us help you

Yes, I'd like to be assigned to work on this item

### PR DESCRIPTION
**Pull request by MatsM16**
**Closes #306**

## PR Checklist

- [x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [x] PR doesn't include merge commits (always rebase on top of our main, if needed)
- [ ] New integration
  - [ ] Docs are written
  - [ ] Added description of major feature to project description for NuGet package (4000 total character limit, so don't push entire description over that)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Every new API (including internal ones) has full XML docs
- [x] Code follows all style conventions

### CODE REVIEW

**Comment by MatsM16** [comment]
Using `.WithContainerRuntimeArgs(...)` instead of `.WithArgs(...)` as the documentation for `WithContainerRuntimeArgs` specifies:
> This is intended to pass additional arguments to the underlying container runtime run command to enable advanced features such as exposing GPUs to the container.  

[Link to documentation](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.containerresourcebuilderextensions.withcontainerruntimeargs?view=dotnet-aspire-9.0)

**Review by aaronpowell — APPROVED** [review]

**Comment by aaronpowell** [comment]
My bad! Once the build passes I'll merge this back to `main` and a new beta will go out

**Comment by MatsM16** [comment]
@aaronpowell sweet!

**Comment by MatsM16** [comment]
I forgot to update the tests

**Comment by aaronpowell** [comment]
> I forgot to update the tests

Yep, you'll need to use `ContainerRuntimeArgsCallbackAnnotation` as the annotation to resolve.

**Review by aaronpowell — APPROVED** [review]

**Comment by aaronpowell** [comment]
Thanks @MatsM16 - merged

**Pull request merged**
