### PR TITLE
Add test base classes

### PR DESCRIPTION
**Pull request by Alirexaa**
**Closes #<ISSUE_NUMBER>**

This pull request introduces several new testing utilities and updates package references in the project. The most important changes include adding new package references, copying testing utilities from other repositories, and implementing new Xunit attributes and discoverers.

### Package Updates:

* [`Directory.Packages.props`](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156R10-R26): Added new package versions for `JsonSchema.Net`, `Microsoft.Extensions.Diagnostics.HealthChecks`, `Microsoft.Extensions.Hosting`, and `OpenTelemetry.Exporter.InMemory`. [[1]](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156R10-R26) [[2]](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156L36)
* [`tests/Aspire.CommunityToolkit.Testing/Aspire.CommunityToolkit.Testing.csproj`](diffhunk://#diff-808be7323c9f69cae1ef749a54e0bb09ae40efbd92bc3cd717f9602eb5aa3d84R17-R22): Added package references for `JsonSchema.Net`, `Microsoft.Extensions.Diagnostics.HealthChecks`, `Microsoft.Extensions.Hosting`, and `OpenTelemetry.Extensions.Hosting`.

### Testing Utilities:

* [`tests/Aspire.CommunityToolkit.Testing/ActivityNotifier.cs`](diffhunk://#diff-ad8f16eb53d066439b6a56d2250b701297a109120bd11903d6a29b4e194a6e1eR1-R58): Added `ActivityNotifier` class, an OpenTelemetry processor to notify callers when an activity is processed.
* [`tests/Aspire.CommunityToolkit.Testing/TestLoggerFactory.cs`](diffhunk://#diff-9c318b8b67f7b992fdc2b4a9fb07bf9fcf56407fe1a3335c0a3a6634b2b32a58R1-R26): Added `TestLoggerFactory` class for creating loggers in tests.

### Xunit Attributes and Discoverers:

* [`tests/Aspire.CommunityToolkit.Testing/Xunit/ConditionalFactAttribute.cs`](diffhunk://#diff-639d73ce3b872c03c28dbe464b354bd4af5eab36096ed18d4763ec604833ce57R1-R16): Added `ConditionalFactAttribute` class for conditionally running tests.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/ConditionalFactDiscoverer.cs`](diffhunk://#diff-ce7cd9bf51496b1877a9c70d4f54522104427c8bfede7b64bafe23d96390beceR1-R29): Added `ConditionalFactDiscoverer` class to discover conditional facts.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/ConditionalTheoryAttribute.cs`](diffhunk://#diff-2bb4ae28ec460077b59a897cbf505efbd921484c4e41fb59139bfe8921a8567eR1-R16): Added `ConditionalTheoryAttribute` class for conditionally running theories.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/ConditionalTheoryDiscoverer.cs`](diffhunk://#diff-2a0b0d7a19cc88af04374d26dd040f8d2fe6a7b06acd3563a7b7058d470726e0R1-R84): Added `ConditionalTheoryDiscoverer` class to discover conditional theories.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/ITestCondition.cs`](diffhunk://#diff-8e2e9af3d9ae35ab37f1bfa0d21560915af0c5db3277a6e5013daf3f6883cdd6R1-R13): Added `ITestCondition` interface for defining test conditions.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/OSSkipConditionAttribute.cs`](diffhunk://#diff-5e2434925a88dd557385563a6b2cdc387a27f56aa1aa9a46f1761c29d78e1388R1-R69): Added `OSSkipConditionAttribute` class to skip tests based on the operating system.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/OperatingSystems.cs`](diffhunk://#diff-29116e7c5200a727118e864c3f1187698326707b8c542a3a5f0464e71398d5b2R1-R16): Added `OperatingSystems` enum to represent different operating systems.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/SkippedTestCase.cs`](diffhunk://#diff-9520effeda0796f94ab468319ebe7e32c4645617ed7a143b161a08ee0799934dR1-R52): Added `SkippedTestCase` class to represent skipped test cases.
* [`tests/Aspire.CommunityToolkit.Testing/Xunit/TestMethodExtensions.cs`](diffhunk://#diff-08cc7b596710853548a5385a00a41c18968d31c8424ed14a56c9e8cfce9370f0R1-R35): Added `TestMethodExtensions` class with extension methods for test methods.

## PR Checklist

- [ ] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [ ] Based off latest main branch of toolkit
- [ ] PR doesn't include merge commits (always rebase on top of our main, if needed)
- [ ] New integration
  - [ ] Docs are written
  - [ ] Added description of major feature to project description for NuGet package (4000 total character limit, so don't push entire description over that)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Every new API (including internal ones) has full XML docs
- [ ] Code follows all style conventions

### CODE REVIEW

**Comment by aaronpowell** [comment]
I believe they come from https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json

We can probably hack around some of this stuff by implementing it ourselves or using different types, but it's a worthwhile conversation to have with the Aspire team about more access to test helpers

**Comment by aaronpowell** [comment]
I've done some digging and those libraries are from https://github.com/dotnet/arcade

Given what they are and their intended use, we should **not** take a dependency on them as it ties the Community Toolkit to .NET engineering, which will be a problem from a governance perspective.

**Comment by Alirexaa** [comment]
@davidfowl, We need some helper classes in [Aspire.Components.Common.Tests](https://github.com/dotnet/aspire/tree/main/tests/Aspire.Components.Common.Tests) to keep community toolkit integration aligned to aspire.
Is it possible to have a Nuget package for this?

**Review by aaronpowell — APPROVED** [review]
Until there's more of this surfaced in the Aspire testing packages, we'll have to bring it over ourselves.

**Comment by Alirexaa** [comment]
I merge this to unblock #66. If any changes are needed #66 will take care of it.

**Pull request merged**
